### ISSUE TITLE
Doesn't work with `Poetry 2.0` if pyproject doesn't have `[tool.poetry]`

### ISSUE THREAD

**Issue by ghost** [galaunay/poetry.el#59]
In the latest version of poetry, the `[tool.poetry]` table is no longer mandatory.

Now it also reads the `[proejct]` table.

So, these two configurations are valid:

```toml
[project]
name = "test"
version = "0.1.0"

requires-python = ">=3.13,<4.0"
dependencies = [
    "numpy (>=2.2.1,<3.0.0)"
]
```

```toml
[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
numpy = "^2.2.1"
```

https://github.com/cybniv/poetry.el/blob/1dff0d4a51ea8aff5f6ce97b154ea799902639ad/poetry.el#L893-L901

The `poetry-find-project-root` function only searches for `[tool.poetry]`, I believe the adjustment should be in this function, but I don't have enough context of the project to know what it would be.

Maybe turn the `poetry check` command?
